apiVersion: v1
kind: ReplicationController
metadata:
  name: my-replication-controller
spec:
  replicas: 3
  selector:
    app: replication-controller
  template:
    metadata:
      labels:
        app: replication-controller
    spec:
      containers:
      - name: replication-controller-container
        image: "gcr.io/wt-gd-pdd2/nginx_test@sha256:9f73124c8bed8af82ae4de85b780954c9bba511fcc517602c73e50aa778665ef"
        ports:
        - containerPort: 3001
